### ISSUE TITLE
how to contact you sury?

### ISSUE THREAD

**Issue by wannaknowmo** [suryagaddipati/jenkins-docker-slaves#8]
currently have an issue with the new docker swarm plugin (1.2)
test connection with the docker swarm api is failing

**Comment by rcreasey** [comment]
Same here; new plugin doesn't have issues setup but you're missing documentation (implementation?) on how to get this working with a tls based swarm connection.  @suryagaddipati?

**Comment by smhc** [comment]
This build supports tls: https://github.com/smhc/docker-swarm-plugin-tls

**Comment by suryagaddipati** [comment]
hi, please follow this issue here. https://github.com/jenkinsci/docker-swarm-plugin/pull/1
